import media#import the media module with contains the Movie class
import fresh_tomatoes#generate the web page

toy_story = media.Movie('Toy Story', "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.", 'http://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg', 'https://www.youtube.com/watch?v=KYz2wyBy3kc','Woody, Buzz, Andy, Molly','John Lasseter')#inicialize a instance of the class Movie with the information about the Toy Story film
avatar = media.Movie('Avatar', "A Paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home...", 'http://upload.wikimedia.org/wikipedia/pt/thumb/b/b0/Avatar-Teaser-Poster.jpg/250px-Avatar-Teaser-Poster.jpg', 'https://www.youtube.com/watch?v=5PSNL1qE6VY','Sam Worthington, Zoe Saldana, Sigourney Weaver','James Cameron')#inicialize a instance of the class Movie with the information about the Avatar film
homem_que_desfiaou_o_diabo = media.Movie('O homem que desafiou o diabo', 'The story of a man that chalanges the devil:In the Northeastern of Brazil, the wolf traveling salesman of fabric Jose Araujo arrives at Jardim dos Caiacos and succeeds in selling his merchandise to the Turkish Turco.','http://wwws.br.warnerbros.com/ohomemquedesafiouodiabo/_i/poster.jpg','https://www.youtube.com/watch?v=XLdq-1p8hfs','Marcos Palmeira, Flavia Alessandra, Livia Falcao','Moacyr Goes')#inicialize a instance of the class Movie with the information about the O homem que desafiou o diabo film
scarface = media.Movie('Scarface','In 1980 Miami, a determined Cuban immigrant takes over a drug cartel while succumbing to greed.','https://www.movieposter.com/posters/archive/main/117/MPW-58950','https://www.youtube.com/watch?v=7pQQHnqBa2E','Al Pacino, Michelle Pfeiffer, Steven Bauer','Brian De Palma')#inicialize a instance of the class Movie with the information about the Scarface film
snatch = media.Movie('Snatch', 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 'http://ia.media-imdb.com/images/M/MV5BMTk5NzE0MDQyNl5BMl5BanBnXkFtZTcwNzk4Mjk3OA@@._V1_SY317_CR2,0,214,317_AL_.jpg', 'https://www.youtube.com/watch?v=ZOocUDuffdI','Jason Statham, Brad Pitt, Benicio Del Toro','Guy Ritchie')#inicialize a instance of the class Movie with the information about the Snatch film
vip = media.Movie('VIPs', 'A compulsive liar making his way up on society', 'http://3.bp.blogspot.com/-O_MdVlRTaZ4/Taug-ONOs7I/AAAAAAAAAY8/BW4p5IVFR2c/s1600/vips-poster.jpg','https://www.youtube.com/watch?v=ROOK2BBIwpA','Wagner Moura, Gisele Froes, Emiliano Ruschel','Toniko Melo')#inicialize a instance of the class Movie with the information about the VIP film

movies = [toy_story, avatar, homem_que_desfiaou_o_diabo, scarface, snatch, vip]
fresh_tomatoes.open_movies_page(movies)
#print(toy_story.__class__.__init__.__doc__)
